/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import type { IGetOptions, IGetAllOptions } from '../models/commonModels';
import type { Buildings } from '../models/BuildingsModel';
import schema from '../../schema/datamodel.schema';

// Simple in-memory operation result interface to match Power Apps SDK
interface IOperationResult<T> {
    success: boolean;
    data?: T;
    error?: any;
}

/* NOTE(ai): DO NOT REMOVE OR MODIFY — In-memory service class
Purpose: UI needs to implement CRUD operations using this service class as is. */

export class BuildingsService {
    private static readonly dataSourceName = 'buildings';
    private static _data: Buildings[] = [];
    private static _nextId = 1;
    private static _isInitialized = false;

    /**
     * Seeds the data source with sample data from schema if the table is empty.
     * This method should be called during app initialization.
     */
    public static async seedSampleData(): Promise<void> {
        try {
            // Get sample data from schema
            const sampleData: any[][] = (schema as any).tableSampleData.building.sampleData;

            // Transform schema sample data to objects
            const seedRecords: Omit<Buildings, 'ID'>[] = sampleData.map(row => ({
                name: row[1],
                location: row[2],
                address: row[3],
                floors: row[4]
            }));

            // Create all sample records
            const createPromises = seedRecords.map(record => this.create(record));
            const results = await Promise.all(createPromises);

            // Log results
            const successCount = results.filter(r => r.success).length;
            const failureCount = results.length - successCount;

            console.log(`Seeding completed: ${successCount} success, ${failureCount} failures`);

            if (failureCount > 0) {
                const errors = results.filter(r => !r.success).map(r => r.error);
                console.error('Seeding errors:', errors);
            }

        } catch (error) {
            console.error('Error during sample data seeding:', error);
        }
    }

    /**
     * Initializes the service and seeds sample data if needed.
     * Call this method when your app starts up.
     */
    public static async initializeWithSampleData(): Promise<void> {
        if (this._isInitialized) {
            return;
        }
        this._isInitialized = true;
        await this.seedSampleData();
    }

    /**
     * Creates a new Buildings record in the in-memory data store.
     *
     * @param record - The Buildings data to create. ID field is automatically generated and should be omitted.
     * @returns A Promise that resolves to an IOperationResult containing the created Buildings with its generated ID,
     *          or error information if the operation fails.
     *
     * @example
     * ```typescript
     * const newBuildings = { name: "Sample Buildings", buildingId: "1234" };
     * const result = await BuildingsService.create(newBuildings);
     * ```
     */
    public static async create(record: Omit<Buildings, 'ID'>): Promise<IOperationResult<Buildings>> {
        try {
            const newRecord: Buildings = {
                ...record,
                ID: this._nextId++
            };

            this._data.push(newRecord);

            return {
                success: true,
                data: newRecord
            };
        } catch (error) {
            return {
                success: false,
                error: 'Failed to create record'
            };
        }
    }

    /**
     * Updates an existing Buildings record in the in-memory data store.
     *
     * @param ID - The unique identifier of the Buildings to update.
     * @param changedFields - An object containing only the fields to be updated. ID field cannot be modified.
     * @returns A Promise that resolves to an IOperationResult containing the updated Buildings,
     *          or error information if the operation fails.
     *
     * @example
     * ```typescript
     * const updatedBuildings = { name: "Updated Buildings", buildingId: "1234" };
     * const result = await BuildingsService.update(Buildings.ID, updatedBuildings);
     * ```
     */
    public static async update(ID: number, changedFields: Partial<Omit<Buildings, 'ID'>>): Promise<IOperationResult<Buildings>> {
        try {
            const index = this._data.findIndex(item => item.ID === ID);

            if (index === -1) {
                return {
                    success: false,
                    error: `Record with ID ${ID} not found`
                };
            }

            const updatedRecord: Buildings = {
                ...this._data[index],
                ...changedFields,
                ID: ID // Ensure ID cannot be changed
            };

            this._data[index] = updatedRecord;

            return {
                success: true,
                data: updatedRecord
            };
        } catch (error) {
            return {
                success: false,
                error: 'Failed to update record'
            };
        }
    }

    /**
     * Deletes a Buildings record from the in-memory data store.
     *
     * @param ID - The unique identifier of the Buildings to delete.
     * @returns A Promise that resolves to an IOperationResult indicating success or failure of the delete operation,
     *          or error information if the operation fails.
     *
     * @example
     * ```typescript
     * const result = await BuildingsService.delete(Buildings.ID);
     * ```
     */
    public static async delete(ID: number): Promise<IOperationResult<void>> {
        try {
            const index = this._data.findIndex(item => item.ID === ID);

            if (index === -1) {
                return {
                    success: false,
                    error: `Record with ID ${ID} not found`
                };
            }

            this._data.splice(index, 1);

            return {
                success: true
            };
        } catch (error) {
            return {
                success: false,
                error: 'Failed to delete record'
            };
        }
    }

    /**
     * Retrieves a single Buildings record by its ID from the in-memory data store.
     *
     * @param ID - The unique identifier of the Buildings to retrieve.
     * @param options - Optional query options for the retrieval operation (e.g., select fields, expand related data).
     * @returns A Promise that resolves to an IOperationResult containing the Buildings,
     *          or error information if the operation fails or the Buildings is not found.
     *
     * @example
     * ```typescript
     * const result = await BuildingsService.get(Buildings.ID);
     * ```
     */
    public static async get(ID: number, options?: IGetOptions): Promise<IOperationResult<Buildings>> {
        try {
            const record = this._data.find(item => item.ID === ID);

            if (!record) {
                return {
                    success: false,
                    error: `Record with ID ${ID} not found`
                };
            }

            return {
                success: true,
                data: { ...record } // Return a copy to prevent external mutations
            };
        } catch (error) {
            return {
                success: false,
                error: 'Failed to retrieve record'
            };
        }
    }

    /**
     * Retrieves all Buildings records from the in-memory data store.
     *
     * @param options - Optional query options for the retrieval operation (e.g., filtering, sorting, pagination).
     * @returns A Promise that resolves to an IOperationResult containing an array of Buildings,
     *          or error information if the operation fails.
     *
     * @example
     * ```typescript
     * const result = await BuildingsService.getAll();
     * ```
     */
    public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<Buildings[]>> {
        try {
            await this.initializeWithSampleData();
            return {
                success: true,
                data: this._data.map(record => ({ ...record })) // Return copies to prevent external mutations
            };
        } catch (error) {
            return {
                success: false,
                error: 'Failed to retrieve records'
            };
        }
    }
}
